# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: build
    displayName: Build Angular application
    jobs:
      - job:
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "10.x"
          - script: npm install
          - script: npm run build 
          - publish: dist
            artifact: dist

  - stage: deploy_dev
    displayName: Deploy to development
    variables:
      - group: Development
    jobs:
      - job:
        steps:
          - script: echo Hello, world!

  - stage: deploy_prod
    displayName: Deploy to production
    variables:
      - group: Production
    jobs:
      - job:
        steps:
          - script: echo Hello, world!
