# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: build
    displayName: Build Angular application
    jobs:
      - job:
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "10.x"
          - script: npm install
          - script: npm run build 
          - task: replacetokens@3
            inputs:
              targetFiles: "$(System.DefaultWorkingDirectory)/dist/**/main*.js"
              encoding: "auto"
              writeBOM: true
              verbosity: "detailed"
              actionOnMissing: "warn"
              keepToken: false
              tokenPrefix: "#{"
              tokenSuffix: "}#"
              useLegacyPattern: false
              enableTelemetry: true
          - publish: $(System.DefaultWorkingDirectory)
            artifact: App
