# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: build
    displayName: Build Angular application
    jobs:
      - job:
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "10.x"
          - script: npm install
          - script: npm run build 
          - publish: 
            artifact: dist

  - stage: deploy_prod
    displayName: Deploy to production
    variables:
      - group: Production
    jobs:
      - deployment: deploy
        environment: Production
        strategy:
          runOnce:
            deploy:
              steps:
                - task: replacetokens@3
                  inputs:
                    targetFiles: "$(Pipeline.Workspace)/dist/**/main*.js"
                    encoding: "auto"
                    writeBOM: true
                    verbosity: "detailed"
                    actionOnMissing: "warn"
                    keepToken: false
                    tokenPrefix: "#{"
                    tokenSuffix: "}#"
                    useLegacyPattern: false
                    enableTelemetry: true
                - task: NodeTool@0
                  inputs:
                    versionSpec: "10.x"
                - script: | 
                    cd $(Pipeline.Workspace)
                    npm install -g firebase-tools
                    firebase deploy --project="$(Firebase Project)" --token "$(Firebase Token)" -m "$(Build.BuildNumber)"
